name: dart_application_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  openfoodfacts_flutter_lints:
    git: https://github.com/g123k/openfoodfacts_flutter_lints.git
 